#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

enum layer_number {
  _QWERTY = 0,
  _COLEMAK,
  _SYMBOL,
  _NAVIGATION,
  _MOUSE
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
/* QWERTY
 * ,-----------------------------------------.                    ,-----------------------------------------.
 * | ESC  |   1  |   2  |   3  |   4  |   5  |                    |   6  |   7  |   8  |   9  |   0  |  `   |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * | Del  |   Q  |   W  |   E  |   R  |   T  |                    |   Y  |   U  |   I  |   O  |   P  |  #   |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |BackSP|   A  |   S  |   D  |   F  |   G  |-------.    ,-------|   H  |   J  |   K  |   L  |   ;  |  '   |
 * |------+------+------+------+------+------|   [   |    |    ]  |------+------+------+------+------+------|
 * |LShift|   Z  |   X  |   C  |   V  |   B  |-------|    |-------|   N  |   M  |   ,  |   .  |   /  |RShift|
 * `-----------------------------------------/       /     \      \-----------------------------------------'
 *                   | LAlt | Tab  | NAV  | /Space  /       \Enter \  |SYMBOL| RGUI |LCtrl |
 *                   |      |      |      |/       /         \      \ |      |      |      |
 *                   `----------------------------'           '------''--------------------'
 */
 [_QWERTY] = LAYOUT(
  KC_ESC,   KC_1,	        KC_2,         KC_3,	  KC_4,   KC_5, 			              KC_6,  KC_7,	KC_8,	    KC_9,	  KC_0,	            KC_GRV,
  KC_DEL,   KC_Q, 	      KC_W,         KC_E,   KC_R,   KC_T, 			              KC_Y,	 KC_U, 	KC_I, 	  KC_O, 	KC_P, 	          KC_NUHS,
  KC_BSPC,  KC_A, 	      KC_S,         KC_D,   KC_F,   KC_G, 			              KC_H,	 KC_J, 	KC_K, 	  KC_L, 	KC_SCLN,          KC_QUOT,
  KC_LSFT,  LCTL_T(KC_Z), LALT_T(KC_X), KC_C,   KC_V, 	KC_B,  KC_LBRC, KC_RBRC,  KC_N,	 KC_M, 	KC_COMM,  KC_DOT, RCTL_T(KC_SLASH), KC_RSFT,
                              KC_LALT, KC_TAB, MO(_NAVIGATION), KC_SPC,	KC_ENT, MO(_SYMBOL), KC_LGUI, DF(_COLEMAK)
 ),

/* COLEMAK
 * ,-----------------------------------------.                    ,-----------------------------------------.
 * | ESC  |   1  |   2  |   3  |   4  |   5  |                    |   6  |   7  |   8  |   9  |   0  |  `   |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * | Del  |   Q  |   W  |   F  |   P  |   B  |                    |   J  |   L  |   U  |   Y  |   ;  |  #   |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |BackSP|   A  |   R  |   S  |   T  |   G  |-------.    ,-------|   M  |   N  |   E  |   I  |   O  |  '   |
 * |------+------+------+------+------+------|   [   |    |    ]  |------+------+------+------+------+------|
 * |LShift|   Z  |   X  |   C  |   D  |   V  |-------|    |-------|   K  |   H  |   ,  |   .  |   /  |RShift|
 * `-----------------------------------------/       /     \      \-----------------------------------------'
 *                   | LAlt | Tab  | NAV  | /Space  /       \Enter \  |SYMBOL| RGUI |LCtrl |
 *                   |      |      |      |/       /         \      \ |      |      |      |
 *                   `----------------------------'           '------''--------------------'
 */
 [_COLEMAK] = LAYOUT(
  KC_ESC,   KC_1,	        KC_2,         KC_3,     KC_4,      KC_5, 			               KC_6,    KC_7,    KC_8,    KC_9,    KC_0,             KC_GRV,
  KC_DEL,   KC_Q, 	      KC_W,         KC_F,     KC_P,      KC_B, 			               KC_J,	  KC_L, 	 KC_U, 	  KC_Y, 	 KC_SCLN, 	       KC_NUHS,
  KC_BSPC,  KC_A, 	      KC_R,         KC_S,     KC_T,      KC_G, 			               KC_M,	  KC_N, 	 KC_E, 	  KC_I, 	 KC_O,             KC_QUOT,
  KC_LSFT,  LCTL_T(KC_Z), LALT_T(KC_X), KC_C,     KC_D, 	   KC_V,  KC_LBRC,  KC_RBRC, KC_K,	  KC_H, 	 KC_COMM, KC_DOT,  RCTL_T(KC_SLASH), KC_RSFT,
                                   KC_LALT, KC_TAB, MO(_NAVIGATION), KC_SPC,	KC_ENT, MO(_SYMBOL), KC_LGUI, DF(_QWERTY)
 ),

/* SYMBOL
 * ,-----------------------------------------.                    ,-----------------------------------------.
 * |   V  |  F1  |  F2  |  F3  |  F4  |  F5  |                    |  F6  |  F7  |  F8  |  F9  |  F10 |  F11 |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |   V  |   !  |   "  |   £  |   $  |   %  |                    |   ^  |   &  |   *  |   (  |   )  |  F12 |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |   V  |   1  |   2  |   3  |   4  |   5  |-------.    ,-------|   \  |   -  |   =  |   [  |   ]  | CAPS |
 * |------+------+------+------+------+------|   [   |    |    ]  |------+------+------+------+------+------|
 * |   V  |   6  |   7  |   8  |   9  |   0  |-------|    |-------|   |  |   _  |   +  |   {  |   }  |   V  |
 * `-----------------------------------------/       /     \      \-----------------------------------------'
 *                   |  V   |  V   | NAV  | /  V    /       \   V  \  |SYMBOL|   V  |   V  |
 *                   |      |      |      |/       /         \      \ |      |      |      |
 *                   `----------------------------'           '------''--------------------'
 */
 [_SYMBOL] = LAYOUT(
  KC_TRNS, KC_F1,   KC_F2,  KC_F3,   KC_F4,  KC_F5,                       KC_F6,      KC_F7,     KC_F8,   KC_F9,   KC_F10,   KC_F11,
  KC_TRNS, KC_EXLM, KC_AT,  KC_HASH, KC_DLR, KC_PERC,                     KC_CIRC,    KC_AMPR,   KC_ASTR, KC_LPRN, KC_RPRN,  KC_F12,
  KC_TRNS, KC_1,    KC_2,   KC_3,    KC_4,   KC_5,                        KC_NUBS,    KC_MINUS,  KC_EQL,  KC_LBRC, KC_RBRC,  KC_CAPS,
  KC_TRNS, KC_6,    KC_7,   KC_8,    KC_9,   KC_0,     KC_NO, KC_NO,      S(KC_NUBS), KC_UNDS,   KC_PLUS, KC_LCBR, KC_RCBR,  KC_TRNS,
                            KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,   KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
 ),

/* NAVIGATION
 * ,-----------------------------------------.                    ,-----------------------------------------.
 * |  V   |      |      |      |      |      |                    |      |      |      |      |      |      |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |  V   |  F1  |  F2  |  F3  |  F4  |  F5  |                    | PgUp | Home	|  Up  | End  |      |      |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |  V   |  F6  |  F7  |  F8  |  F9  |  F10 |-------.    ,-------| PgDn | Left | Down | Right| >/II |      |
 * |------+------+------+------+------+------|       |    |       |------+------+------+------+------+------|
 * |  V   |  V   |      |      |  F11 |  F12 |-------|    |-------|      |    	|      |      | RCtl |  V   |
 * `-----------------------------------------/       /     \      \-----------------------------------------'
 *                   |  V   |  V   | NAV  | /  V    /       \   V  \  |SYMBOL|   V  |   V  |
 *                   |      |      |      |/       /         \      \ |      |      |      |
 *                   `----------------------------'           '------''--------------------'
 */
 [_NAVIGATION] = LAYOUT(
  KC_TRNS, KC_NO,   KC_NO,  KC_NO,  KC_NO,  KC_NO,                     KC_NO,   KC_NO,   KC_NO,   KC_NO,    KC_NO,               KC_NO,
  KC_TRNS, KC_F1,   KC_F2,  KC_F3,  KC_F4,  KC_F5,                     KC_PGUP, KC_HOME, KC_UP,   KC_END,   KC_NO,               KC_NO,
  KC_TRNS, KC_F6,   KC_F7,  KC_F8,  KC_F9,  KC_F10,                    KC_PGDN, KC_LEFT, KC_DOWN, KC_RIGHT, KC_MEDIA_PLAY_PAUSE, KC_NO,
  KC_TRNS, KC_LCTL, KC_NO,  KC_NO,  KC_F11, KC_F12,   KC_NO,  KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,    KC_RCTL,             KC_TRNS,
                        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,    KC_TRNS, KC_TRNS, KC_TRNS,  KC_TRNS
 ),

 /* MOUSE
 * ,-----------------------------------------.                    ,-----------------------------------------.
 * |   V  |      |      |      |      |      |                    |      |      |      |      |      |      |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |   V  |      |      |  MUp |      |      |                    |      |      |      |      |      |      |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |   V  |      | MLeft|  MDn |MRight|      |-------.    ,-------|      |  M1  |  M2  |  M3  |      |      |
 * |------+------+------+------+------+------|       |    |       |------+------+------+------+------+------|
 * |   V  | LCtl |      |      |      |      |-------|    |-------|      |      |      |      | RCtl |   V  |
 * `-----------------------------------------/       /     \      \-----------------------------------------'
 *                   |  V   |  V   | NAV  | /  V    /       \   V  \  |SYMBOL|   V  |   V  |
 *                   |      |      |      |/       /         \      \ |      |      |      |
 *                   `----------------------------'           '------''--------------------'
 */
 [_MOUSE] = LAYOUT(
  KC_TRNS,   KC_NO,	  KC_NO,   KC_NO,	KC_NO,   KC_NO, 			     KC_NO,  KC_NO,	  KC_NO,   KC_NO,   KC_NO,	 KC_NO,
  KC_TRNS,   KC_NO,   KC_NO,   KC_MS_U, KC_NO, 	 KC_NO, 			     KC_NO,	 KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,
  KC_TRNS,   KC_NO,   KC_MS_L, KC_MS_D, KC_MS_R, KC_NO, 			     KC_NO,	 KC_BTN1, KC_BTN2, KC_BTN3, KC_NO,   KC_NO,
  KC_TRNS,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,  KC_NO,  KC_NO,  KC_NO,	 KC_NO,   KC_NO,   KC_NO,   KC_RCTL, KC_TRNS,
                KC_TRNS, KC_TRNS, MO(_NAVIGATION), KC_TRNS,	KC_TRNS, MO(_SYMBOL), KC_TRNS, KC_TRNS
 ),
};

layer_state_t layer_state_set_user(layer_state_t state) {
  return update_tri_layer_state(state, _SYMBOL, _NAVIGATION, _MOUSE);
}

//SSD1306 OLED update loop, make sure to enable OLED_ENABLE=yes in rules.mkS
#ifdef OLED_ENABLE

oled_rotation_t oled_init_user(oled_rotation_t rotation) {
  if (is_keyboard_master())
    return OLED_ROTATION_270;  // flips the display 180 degrees if offhand
  else
    return OLED_ROTATION_180;
}

// When you add source files to SRC in rules.mk, you can use functions.
const char* read_layer_state(void);
const char* read_logo(void);
void set_keylog(uint16_t keycode, keyrecord_t* record);
const char* read_keylog(void);
//const char *read_keylogs(void);
//static const char* mando_logo(void);

//const char* read_mode_icon(bool swap);
// const char *read_host_led_state(void);
// void set_timelog(void);
// const char *read_timelog(void);

// oled_rotation_t oled_init_user(oled_rotation_t rotation) {
// 	if (is_keyboard_master()) {
// 		return OLED_ROTATION_90;
// 	}

// 	return rotation;
// }

bool oled_task_user(void) {
  if (is_keyboard_master()) {
    // If you want to change the display of OLED, you need to change here
    //oled_write_ln(read_layer_state(), false)
    oled_write_P(PSTR("-----"), false);
	switch (get_highest_layer(layer_state|default_layer_state))
	{
		case _QWERTY:
			oled_write_ln_P(PSTR("Base"), false);
			break;

    case _COLEMAK:
      oled_write_ln_P(PSTR("CLMK"), false);
      break;

		case _SYMBOL:
			oled_write_ln_P(PSTR("Symb"), false);
			break;

		case _NAVIGATION:
			oled_write_ln_P(PSTR("Nav"), false);
			break;

    case _MOUSE:
      oled_write_P(PSTR("Mouse"), false);
      break;
	}
    oled_write_P(PSTR("-----"), false);
    oled_write_ln(read_keylog(), false);
    //oled_write_ln(read_keylogs(), false);
    //oled_write_ln(read_mode_icon(keymap_config.swap_lalt_lgui), false);
    //oled_write_ln(read_host_led_state(), false);
    //oled_write_ln(read_timelog(), false);
  } else {
    oled_write_P(read_logo(), false);
  }
    return false;
}
#endif // OLED_ENABLE

bool process_record_user(uint16_t keycode, keyrecord_t* record) {
  if (record->event.pressed) {
#ifdef OLED_ENABLE
    set_keylog(keycode, record);
#endif
    // set_timelog();
  }
  return true;
}

// #if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
// const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

// };
// #endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)

// static const char* mando_logo(void) {
//     static const char PROGMEM logo[] = {
//         // 'Mandalorian Logo', 32x128px
//         0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
//         0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
//         0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
//         0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
//         0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
//         0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
//         0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
//         0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
//         0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
//         0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
//         0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xe2, 0x01, 0xff, 0xff, 0xc0, 0x01, 0xff,
//         0xff, 0xc4, 0x01, 0xff, 0xff, 0xc2, 0x01, 0xff, 0xff, 0xc2, 0x01, 0xff, 0xff, 0xe0, 0x02, 0xff,
//         0xff, 0xb0, 0x04, 0xff, 0xff, 0x38, 0x1c, 0xff, 0xff, 0x3c, 0x3c, 0xff, 0xff, 0x3c, 0x78, 0xff,
//         0xff, 0x1c, 0x70, 0xff, 0xff, 0x0c, 0x40, 0xff, 0xff, 0x84, 0x01, 0x3f, 0xff, 0x80, 0x02, 0x1f,
//         0xf8, 0xc0, 0x02, 0x0f, 0xf8, 0x60, 0x06, 0x07, 0xf0, 0x10, 0x0c, 0x07, 0xe0, 0x10, 0x0e, 0x03,
//         0xc0, 0x30, 0x0f, 0x03, 0xc0, 0xf0, 0x0f, 0x81, 0x81, 0xfa, 0x4f, 0xc1, 0x83, 0xfa, 0x5f, 0xe0,
//         0x87, 0xfa, 0x1f, 0xe0, 0x0f, 0xf8, 0x9f, 0xf0, 0x0f, 0xf0, 0x9f, 0xf0, 0x0f, 0xf1, 0x1f, 0xf0,
//         0x1f, 0xf1, 0x1f, 0xf0, 0x0f, 0xf1, 0x1f, 0xf0, 0x8f, 0xf9, 0x1f, 0xe1, 0x8f, 0xf4, 0x3f, 0x81,
//         0xc1, 0xf2, 0x4f, 0x07, 0xe0, 0x72, 0x4f, 0xff, 0xf9, 0xf0, 0x4f, 0xff, 0xff, 0xf1, 0x4f, 0xff,
//         0xff, 0xf9, 0x4f, 0xff, 0xff, 0xf9, 0x4f, 0xff, 0xff, 0xfd, 0x5f, 0xff, 0xff, 0xfd, 0x1f, 0xff,
//         0xff, 0xfd, 0x1f, 0xff, 0xff, 0xf9, 0x1f, 0xff, 0xff, 0xf9, 0x1f, 0xff, 0xff, 0xf9, 0x1f, 0xff,
//         0xff, 0xf9, 0x3f, 0xff, 0xff, 0xfd, 0x7f, 0xff, 0xff, 0xff, 0x7f, 0xff, 0xff, 0xff, 0xff, 0xff,
//         0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
//         0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
//         0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
//         0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
//         0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
//         0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
//         0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
//         0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
//         0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
//         0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff
//     };
//     return logo;
// }
